name: sweepline_intersections
description: A small and fast module using a sweepline algorithm to detect intersections between polygons and/or polylines.
version: 0.0.4

environment:
  sdk: ">=2.17.5 <4.0.0"
homepage: https://github.com/dartclub/sweepline_intersections
repository: https://github.com/dartclub/sweepline_intersections

dependencies:
  turf: ^0.0.8
  dart_sort_queue: ^0.0.2+3
  collection: ^1.16.0
  benchmark: ^0.3.0
  
dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0

