name: sweepline_intersections
description: A small and fast module using a sweepline algorithm to detect intersections between polygons and/or polylines.
version: 0.0.3
environment:
  sdk: ">=2.17.5 <3.0.0"
homepage: https://github.com/dartclub/sweepline_intersections
repository: https://github.com/dartclub/sweepline_intersections

dev_dependencies:
  dartclub_lint: ^0.4.2
  test: ^1.16.0

dependencies:
  turf: ^0.0.7
  dart_sort_queue: ^0.0.2+3
  collection: ^1.16.0
  benchmark: ^0.3.0
